server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Routing SPA : toute route inconnue renvoie index.html (Angular gère la suite).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
